### ISSUE TITLE
ember s bug in Windows develop environment

### ISSUE THREAD

**Issue by ghost** [null-null-null/ember-progress-bar#4]
The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory:
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\node_modul                    es\broccoli-sane-watcher\index.js:90:11)
    at C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\node_modules\ember-cli-broccoli\lib\builder.js:95:35
    at tryCatch (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:553:13)
    at C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:628:16
    at flush (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-progress-bar\node_modules\broccoli-funnel\node_mod                    ules\broccoli-plugin\index.js:7:31)
    at new Funnel (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-progress-bar\node_modules\broccoli-funnel\index.js:58                    :10)
    at CoreObject.treeForVendor (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-progress-bar\index.js:24:12)
    at CoreObject._treeFor (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\lib\models\addon.js:373:33)
    at CoreObject.treeFor (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\lib\models\addon.js:341:21)
    at C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\lib\broccoli\ember-app.js:498:20
    at Array.map (native)
    at EmberApp.addonTreesFor (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\lib\broccoli\ember-app.js:496:30)
    at EmberApp._processedVendorTree (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\lib\broccoli\ember-app.js:945:                    29)
    at EmberApp._processedExternalTree (C:\Users\fei\dkcf-emberjs-clone\dkcf-emberjs-clone\node_modules\ember-cli\lib\broccoli\ember-app.js:97                    5:21)

**Comment by yanzixiang** [comment]
@jida620 same here,fix in 3 step
1.in \node_modules\ember-progress-bar\index.js
```javascript
  treeForVendor: function() {
    //var treePath = path.dirname(require.resolve('progressbar.js')).split('/').slice(0, -1).join('/');
    //return new Funnel(treePath, {
    //  destDir: 'progressbar.js'
    //});
  },
```
2.copy progressbar.js dir to vendor

3.in ember-cli-build.js
```javascript
app.import('vendor/progressbar.js/dist/progressbar.js');
```

**Comment by Alonski** [comment]
@patience-tema-baron 
Any plans to fix this? I am currently using a fork of this and keeping it updated whenever you push something new.

**Comment by Alonski** [comment]
@patience-tema-baron Anything?

**Comment by briarsweetbriar** [comment]
Hi @Alonski! If you've got a working fork of this, I'd be happy to review a PR. Let me know.

**Comment by justinross** [comment]
Updating to v1.0.0 seems to have resolved this issue for me.
